var ENGLISH_CONSTANTS = {
    BASE_URL: "http://96.45.94.53/",
	//BASE_URL: "http://192.168.20.139:8080/",
    //BASE_URL: "http://192.168.20.55:8080/",
//	BASE_URL: "http://192.168.20.207:8080/",
    SITE_TITLE: "Doctor Visit 247",
    SELECT_LANGUAGE: "Select your language",
    EMERGENCY: "IF THIS IS AN EMERGENCY",
    CALL_911: "PLEASE CALL 911",
    DIAL_911: "DIAL 911",
    ABOUT_US: "ABOUT US",
    PRACTITIONERS: "PRACTIONERS",
    OUR_SERVICES: "OUR SERVICES",
    REQUEST_VISIT: " REQUEST A VISIT",
    STEP_ONE: "step one",
    STEP_TWO: "step two",
    STEP_THREE: "step three",
	PATIENT_INFO: "Patient Information",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    PHONE: "Phone #",
    EMAIL: "Email",
	AMOUNT: "Amount (USD)",
	CARD_NUMBER: "Card Number",
	CVV: "CVV",
	CARD_EXPIRY: "Card Expiry (mmyy)",
    PAYMENT_SUBMIT: "Secure Practioner Visit Payment",
    CALL_US: "Call Us Now!",
    NEXT_STEP: "NEXT STEP",
    CONTINUE: "Continue",
    PAYMENT_FORM_HEAD: "Payment & Reservation",
    PAYMENT_FORM_FOOTER: "This payment only covers initial visit from our practitioner only.",
    ABOUT_FIRST_LINE: "PHYSICIAN CARE IN THE COMFORT OF YOUR OWN HOME, WORKPLACE OR HOTEL ROOM.",
    ABOUT_SECOND_LINE: "OUR DISCREET PRACTITIONERS WILL COME TO YOU 24 HOURS 7 DAYS A WEEK TO YOUR HOME, HOTEL/RESORT OR SOUTH FLORIDA LOCATION AND PROVIDE TOP QUALITY MEDICAL CARE TO YOU NIGHT OR DAY.",
    ABOUT_THIRD_LINE: "TREATMENTS CAN BE ON A ONE-TIME, PER-NEED OR CONTINUOUS BASIS. THERE ARE NO SECRETARIES, NO NURSES, NO AMBULANCES OR WAITING FOR CARE.",
    ABOUT_FOURTH_LINE: "EMERGENCIES ARISE WITHOUT WARNING OR NOTICE. OUR PRACTITIONERS PROVIDE FAST RESPONSE TIMES AND CAN PROVIDE TREATMENT MUCH QUICKER THEN GOING TO THE ER OR FINDING THE LOCAL HOSPITAL",
    PRAC_NAME: "Dr. Elizabeth J Isalguez",
    PRAC_QUALIFICATION: "Internist",
    PRAC_EXPERIENCE: "11 years of experience",
    PRAC_SPECIALITY_LBL: "Specialties",
    PRAC_SPECIALITY_VAL: "Internal Medicine",
    PRAC_CERTIFICATION_LBL: "Certifications",
    PRAC_CERTIFICATION_VAL: "Board Certified",
    PRAC_LANGUAGE_LBL: "Languages",
    PRAC_LANGUAGE_VAL: "English / French / Spanish",
    PRAC_ABOUT: "Dr. Elizabeth Janet Isalguez is a multilingual Medical Doctor in Internal Medicine from the rigorous Yale University program at Bridgeport Hospital. She is fluent in Spanish and French in addition to her native English. Her specific interests include: tropical disease, weight management and nutrition, improving health and vitality from the basic core.",
    LOCATION: "Patient's Location",
    UNIT: "Suite/Apt/Unit",
    STREET: "Street",
    CITY: "City",
    ZIPCODE: "Zip Code",
    DIRECTIONS: "Special Directions",
    
    
    API_STATES: "geoipproximity/statesByCountry?countryAbbrv=",
    API_CITIES: "geoipproximity/citiesByState?stateAbbrv=",
    MSG_INVALID_USERNAME_PWD: "The authentication credentials provided were invalid.",
    MSG_TOO_MANY_REQUESTS: "Number of failed login attempts exceeded",
    MSG_EMPTY_USERNAME_PWD: "Please enter username and password.",
	TAG_ID_RECENTLY_UPDATED_DOMAINS : "RecentlyUpdatedDomains",
	TAG_ID_DOMAINS_LIST : "#RecentlyUpdatedDomainsList",
	TAG_ID_UNCOMMITED_DOMAINS : "UncommitedDomains",
    TAG_RECENTLY_UPDATED_DOMAINS_VIEW_ALL: "VIEW ALL DOMAINS",
	TAG_UNCOMMITED_CHANGES_VIEW_ALL: "VIEW ALL",
    MSG_DOMAIN_NAME_REQUIRED: "Domain name is required",
    MSG_DELETE_CONFIRM: "Are you sure you want to delete?",
	MSG_DELETE_RECORDS: "Are you sure you want to delete all records in this domain?",
    MSG_ACTION_FAILED: "Due to an unexpected error, our server is unable to perform the action. Please try again later.",
    MSG_RECORD_NOT_EXIST: "Record not found.",
    DELETE_SUCCESSFUL: 'Deleted successfully',
    DELETE_FAILED:'Delete failed, please try again later',
    MSG_SESSION_TIMEOUT: "Your current session has timed out. Please login again to continue using the app.",
    MSG_FILL_ALL_FIELDS: "Please fill all fields marked with *",
    MSG_COMMIT_CONFIRM: "Are you sure you want to commit?",
    MSG_DELETE_POOL: " will be removed. Do you want to proceed ?",
    MSG_DELETE_VANITY: "Are you sure you want to delete Vanity Nameserver(s)?",
    MSG_DELETE_GEO_PROXIMITY: "Are you sure you want to delete the GeoIP Proximity?",
    MSG_NO_CHANGES: "No changes to save",
    RECORD_STANDARD: "Standard",
    RECORD_FAILOVER: "Failover",
    RECORD_POOLS: "Pools",
    RECORD_ROUNDROBIN: "Roundrobin with Failover",
    TYPE_A: "A",
    TYPE_AAAA: "AAAA",
    TYPE_CNAME: "CNAME",
    TYPE_MX: "MX",
    TYPE_SPF: "SPF",
    TYPE_NS: "NS",
    TYPE_SRV: "SRV",
    TYPE_PTR: "PTR",
    TYPE_TXT: "TXT",
    POOL_A: "ARecordPool",
    POOL_AAAA: "AAAAPool",
    POOL_CNAME: "CNamePool",
    TAG_DOMAIN: "domain",
    TAG_TEMPLATE: "template",
    TAG_VANITY: "Vanity Nameserver",
    TAG_NONE: "none",
    ALERT: "Alert",
    OK: "OK",
    SUCCESS: "Success",
    CANCEL: "Cancel",
    EXIT: "Exit",
    DELETE: "Delete",
	VERSION: "1.0.0",
	SAVE_RECORD: "Added",
	DELETE_RECORD: "Deleted",
	UPDATE_RECORD: "Updated"
}
var SPANISH_CONSTANTS = {
    SELECT_LANGUAGE: "Elige tu idioma",
    EMERGENCY: "SI ESTO ES UNA EMERGENCIA",
    CALL_911: "POR FAVOR LLAME AL 911",
    DIAL_911: "Dial 911",
    ABOUT_US: "Acerca de nosotros",
    PRACTITIONERS: "practicantes",
    OUR_SERVICES: "Nuestros servicios",
    REQUEST_VISIT: "Solicitar una visita",
    STEP_ONE: "Paso uno",
    STEP_TWO: "Paso dos",
    STEP_THREE: "Paso tres",
	PATIENT_INFO: "Información del paciente",
    FIRST_NAME: "Nombre de pila",
    LAST_NAME: "Apellido",
    PHONE: "Teléfono #",
    EMAIL: "Email",
	AMOUNT: "cantidad (USD)",
	CARD_NUMBER: "Número de tarjeta",
	CVV: "CVV",
	CARD_EXPIRY: "Tarjeta de caducidad (mmyy)",
    PAYMENT_SUBMIT: "Asegure Practioner Visita Pago",
    CALL_US: "Llámanos ahora!",
    NEXT_STEP: "EL PRÓXIMO PASO",
    CONTINUE: "Continuar",
    PAYMENT_FORM_HEAD: "Pago y reserva",
    PAYMENT_FORM_FOOTER: "Este pago sólo cubre visita inicial de sólo nuestro médico.",
    ABOUT_FIRST_LINE: "Cuidado médico en la comodidad de su propio hogar , lugar de trabajo o habitación de hotel.",
    ABOUT_SECOND_LINE: "Nuestros practicantes discretos vendrán a usted las 24 horas 7 días a la semana a su casa , hotel / resort o ubicación del Sur de la Florida y brindar atención médica de alta calidad para usted día o de noche.",
    ABOUT_THIRD_LINE: "Los tratamientos pueden ser en una sola vez , en la necesidad por o de forma continua. No hay secretarias, no hay enfermeras, no hay ambulancias o de espera para la atención.",
    ABOUT_FOURTH_LINE: "Emergencias surgen sin previo aviso o notificación . Nuestros practicantes proporcionan tiempos de respuesta rápidos y pueden proporcionar un tratamiento mucho más rápido y luego ir a la sala de emergencias o encontrar el hospital local.",
    PRAC_NAME: "Dr. Elizabeth J Isalguez",
    PRAC_QUALIFICATION: "internista",
    PRAC_EXPERIENCE: "11 años de experiencia",
    PRAC_SPECIALITY_LBL: "especialidades",
    PRAC_SPECIALITY_VAL: "Medicina Interna",
    PRAC_CERTIFICATION_LBL: "Certificaciones",
    PRAC_CERTIFICATION_VAL: "Certificado por la Junta",
    PRAC_LANGUAGE_LBL: "idiomas",
    PRAC_LANGUAGE_VAL: "English / French / Spanish",
    PRAC_ABOUT: "Dr. Elizabeth Janet Isalguez es un Médico multilingüe en Medicina Interna del programa de la Universidad de Yale rigurosa en el Hospital Bridgeport . Habla con fluidez el español y el francés , además de su nativo de Inglés . Sus intereses específicos incluyen: enfermedades tropicales , control de peso y nutrición , mejorar la salud y la vitalidad del núcleo básico.",
    LOCATION: "Ubicación del paciente",
    UNIT: "Suite / Apt / Unidad",
    STREET: "callejero",
    CITY: "Ciudad",
    ZIPCODE: "Código postal",
    DIRECTIONS: "Direcciones especiales"
}

var FRENCH_CONSTANTS = {
    SELECT_LANGUAGE: "Choisissez votre langue",
    EMERGENCY: "Si cela est une URGENCE",
    CALL_911: "S'IL VOUS PLAÎT APPEL 911",
    DIAL_911: "Composez le 911",
    ABOUT_US: "A propos de nous",
    PRACTITIONERS: "Les praticiens",
    OUR_SERVICES: "Nos services",
    REQUEST_VISIT: "Demander une visite",
    STEP_ONE: "la première étape",
    STEP_TWO: "la deuxième étape",
    STEP_THREE: "la troisième étape",
	PATIENT_INFO: "information pour les patients",
    FIRST_NAME: "Prénom",
    LAST_NAME: "Nom de famille",
    PHONE: "Phone #",
    EMAIL: "Email",
	AMOUNT: "Montant (USD)",
	CARD_NUMBER: "Numéro de carte",
	CVV: "CVV",
	CARD_EXPIRY: "Date d'expiration (mmyy)",
    PAYMENT_SUBMIT: "Fixez Practioner Visitez paiement",
    CALL_US: "Appelez-nous maintenant!",
    NEXT_STEP: "PROCHAINE ÉTAPE",
    CONTINUE: "continuer",
    PAYMENT_FORM_HEAD: "Paiement & Réservation",
    PAYMENT_FORM_FOOTER: "Ce paiement ne couvre que la première visite de notre praticien seulement.",
    ABOUT_FIRST_LINE: "Médecin de soins dans le confort de votre propre maison , au travail ou chambre d'hôtel.",
    ABOUT_SECOND_LINE: "Nos praticiens discrets viendront à vous 24 heures 7 jours par semaine à votre domicile , hôtel / complexe ou l'emplacement sud de la Floride et de fournir des soins médicaux de qualité supérieure pour vous nuit ou le jour.",
    ABOUT_THIRD_LINE: "Les traitements peuvent être sur une seule fois , par - nécessité ou de manière continue . Il n'y a pas pas de secrétaires, infirmières, pas d'ambulances ou en attente de soins.",
    ABOUT_FOURTH_LINE: "Urgences surviennent sans avertissement ni préavis. Nos praticiens fournissent des temps de réponse rapides et peuvent fournir un traitement beaucoup plus rapide d'aller ensuite à l'urgence ou de trouver l'hôpital local .",
    PRAC_NAME: "Dr. Elizabeth J Isalguez",
    PRAC_QUALIFICATION: "interniste",
    PRAC_EXPERIENCE: "11 ans d'expérience",
    PRAC_SPECIALITY_LBL: "spécialités",
    PRAC_SPECIALITY_VAL: "Médecine interne",
    PRAC_CERTIFICATION_LBL: "Certifications",
    PRAC_CERTIFICATION_VAL: "Board Certified",
    PRAC_LANGUAGE_LBL: "langues",
    PRAC_LANGUAGE_VAL: "English / French / Spanish",
    PRAC_ABOUT: "Dr Elizabeth Janet Isalguez est Docteur en Médecine multilingue en médecine interne de l' Université de Yale programme rigoureux à l'hôpital de Bridgeport . Elle parle couramment l'espagnol et le français en plus de sa langue maternelle anglaise . Ses intérêts spécifiques comprennent : les maladies tropicales , la gestion du poids et de la nutrition , l'amélioration de la santé et de la vitalité du noyau de base.",
    LOCATION: "Localisation du patient",
    UNIT: "Suite / Apt / Unité",
    STREET: "de rue",
    CITY: "Ville",
    ZIPCODE: "Code postal",
    DIRECTIONS: "Indications spéciales"
}

var JSON_CONSTANTS = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE",
    CONTENT_TYPE: "text/json",
    DATA_TYPE: "json",
    ACCEPT: "text/json",
    STATUS_CODE_404: "404",
    STATUS_CODE_401: "401",
    STATUS_CODE_403: "403",
    STATUS_CODE_302: "302",
}